### PR TITLE
update dictionary

### PR DESCRIPTION
**Pull request by ausHaus**

### CODE REVIEW

**Comment by Apollon77** [comment]
Do this really work with translations? The fieldnames "name", "id_" and "property" are correct on their lowercase writing ... Code-wise this PR seems to be wrong

**Comment by ausHaus** [comment]
http://forum.iobroker.net/posting.php?mode=edit&f=27&t=6634&p=68819#preview

**Comment by Apollon77** [comment]
Link goes to edit mode in forum, so not intended, or ?!

**Comment by Apollon77** [comment]
hehe, yes you are right. oversaw this righ at the bottom of admin.html:-)

**Comment by Apollon77** [comment]
0.4.1 on github

**Pull request merged**
